// SimplyBudgetWeb.Web/src/pages/History.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { apiClient } from '@/services/apiClient'
import { useSnackbarStore } from '@/stores/snackbar'
import type { HistoryItemDto, ExpenseCategoryDto } from '@/types'
import { formatCents, formatMonth } from '@/utils/currency'
import AddTransactionDialog from '@/components/AddTransactionDialog.vue'

const snackbar = useSnackbarStore()

const now = new Date()
const currentMonth = ref(new Date(now.getFullYear(), now.getMonth(), 1))
const search = ref('')
const categoryId = ref<number | null>(null)
const items = ref<HistoryItemDto[]>([])
const categories = ref<ExpenseCategoryDto[]>([])
const loading = ref(false)
const deleteItem = ref<HistoryItemDto | null>(null)
const dialogOpen = ref(false)

const monthLabel = computed(() =>
  currentMonth.value.toLocaleString('default', { month: 'long', year: 'numeric' }),
)

const categoryOptions = computed(() => [{ id: null, name: 'All' }, ...categories.value])

async function fetchCategories() {
  try {
    categories.value = await apiClient.get<ExpenseCategoryDto[]>('/api/expense-categories')
  } catch { /* ignore */ }
}

async function fetchHistory() {
  loading.value = true
  try {
    const month = `${formatMonth(currentMonth.value)}-01`
    const params = new URLSearchParams({ month })
    if (search.value) params.set('search', search.value)
    if (categoryId.value !== null) params.set('categoryId', String(categoryId.value))
    items.value = await apiClient.get<HistoryItemDto[]>(`/api/history?${params}`) ?? []
  } catch {
    snackbar.enqueueSnackbar('Failed to load history', { variant: 'error' })
  } finally {
    loading.value = false
  }
}

function prevMonth() {
  const d = currentMonth.value
  currentMonth.value = new Date(d.getFullYear(), d.getMonth() - 1, 1)
}

function nextMonth() {
  const d = currentMonth.value
  currentMonth.value = new Date(d.getFullYear(), d.getMonth() + 1, 1)
}

async function handleDelete() {
  if (!deleteItem.value) return
  try {
    await apiClient.delete(`/api/history/${deleteItem.value.id}`)
    snackbar.enqueueSnackbar('Transaction deleted', { variant: 'success' })
    deleteItem.value = null
    void fetchHistory()
  } catch {
    snackbar.enqueueSnackbar('Failed to delete transaction', { variant: 'error' })
  }
}

function totalForItem(item: HistoryItemDto) {
  return item.details.reduce((sum, d) => sum + d.amount, 0)
}

watch([currentMonth, search, categoryId], fetchHistory)

onMounted(() => {
  void fetchCategories()
  void fetchHistory()
})

function onDialogSuccess() {
  void fetchHistory()
  dialogOpen.value = false
}
</script>

<template>
  <div>
    <h5 class="text-h5 mb-4">History</h5>

    <v-card class="pa-4 mb-4 d-flex flex-wrap align-center" style="gap: 16px;">
      <v-btn variant="outlined" size="small" prepend-icon="mdi-chevron-left" @click="prevMonth">Prev</v-btn>
      <span style="min-width: 140px; text-align: center;">{{ monthLabel }}</span>
      <v-btn variant="outlined" size="small" append-icon="mdi-chevron-right" @click="nextMonth">Next</v-btn>

      <v-text-field label="Search" v-model="search" density="compact" style="max-width: 200px;" hide-details />

      <v-select
        label="Category"
        :items="categoryOptions"
        item-title="name"
        item-value="id"
        v-model="categoryId"
        density="compact"
        style="max-width: 200px;"
        hide-details
      />
    </v-card>

    <div v-if="loading" class="d-flex justify-center pa-8">
      <v-progress-circular indeterminate aria-label="Loading history" />
    </div>
    <v-list v-else>
      <v-list-item v-if="items.length === 0">
        <v-list-item-title>No transactions found.</v-list-item-title>
      </v-list-item>
      <v-card v-for="item in items" :key="item.id" class="mb-2">
        <v-list-item>
          <v-list-item-title>
            <div class="d-flex justify-space-between align-center">
              <span>
                {{ new Date(item.date).toLocaleDateString() }} — {{ item.description }}
                <v-chip v-if="item.isTransfer" size="small" class="ml-2">Transfer</v-chip>
              </span>
              <span class="font-weight-bold">{{ formatCents(totalForItem(item)) }}</span>
            </div>
          </v-list-item-title>
          <v-list-item-subtitle>
            <div class="d-flex flex-wrap mt-1" style="gap: 4px;">
              <v-chip v-for="d in item.details" :key="d.id" size="small" variant="outlined">
                {{ d.categoryName }}: {{ formatCents(d.amount) }}
              </v-chip>
            </div>
          </v-list-item-subtitle>
          <template #append>
            <v-btn icon="mdi-delete" variant="text" color="error" aria-label="Delete transaction" @click="deleteItem = item" />
          </template>
        </v-list-item>
      </v-card>
    </v-list>

    <v-btn
      icon="mdi-plus"
      color="primary"
      aria-label="Add Transaction"
      style="position: fixed; bottom: 32px; right: 32px; z-index: 100;"
      @click="dialogOpen = true"
    />

    <AddTransactionDialog v-model="dialogOpen" :categories="categories" @success="onDialogSuccess" />

    <v-dialog :model-value="!!deleteItem" max-width="480" @update:model-value="(val: boolean) => !val && (deleteItem = null)">
      <v-card>
        <v-card-title>Confirm Delete</v-card-title>
        <v-card-text>Delete transaction "{{ deleteItem?.description }}"?</v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="deleteItem = null">Cancel</v-btn>
          <v-btn color="error" @click="handleDelete">Delete</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

// SimplyBudgetWeb.Web/src/pages/History.tsx
import { useState, useEffect, useCallback } from 'react'
import {
  Box, Typography, Button, TextField, MenuItem, Select, InputLabel,
  FormControl, Paper, CircularProgress, List, ListItem, ListItemText,
  IconButton, Chip, Fab, Tooltip, Dialog, DialogTitle, DialogContent,
  DialogContentText, DialogActions,
} from '@mui/material'
import { ChevronLeft, ChevronRight, Delete, Add } from '@mui/icons-material'
import { useSnackbar } from 'notistack'
import { apiClient } from '@/services/apiClient'
import { HistoryItemDto, ExpenseCategoryDto } from '@/types'
import { formatCents, formatMonth } from '@/utils/currency'
import AddTransactionDialog from '@/components/AddTransactionDialog'

export default function History() {
  const [currentMonth, setCurrentMonth] = useState<Date>(() => {
    const now = new Date()
    return new Date(now.getFullYear(), now.getMonth(), 1)
  })
  const [search, setSearch] = useState('')
  const [categoryId, setCategoryId] = useState<number | ''>('')
  const [items, setItems] = useState<HistoryItemDto[]>([])
  const [categories, setCategories] = useState<ExpenseCategoryDto[]>([])
  const [loading, setLoading] = useState(false)
  const [deleteItem, setDeleteItem] = useState<HistoryItemDto | null>(null)
  const [dialogOpen, setDialogOpen] = useState(false)
  const { enqueueSnackbar } = useSnackbar()

  const fetchCategories = useCallback(async () => {
    try {
      const data = await apiClient.get<ExpenseCategoryDto[]>('/api/expense-categories')
      setCategories(data)
    } catch { /* ignore */ }
  }, [])

  const fetchHistory = useCallback(async () => {
    setLoading(true)
    try {
      const month = `${formatMonth(currentMonth)}-01`
      const params = new URLSearchParams({ month })
      if (search) params.set('search', search)
      if (categoryId !== '') params.set('categoryId', String(categoryId))
      const data = await apiClient.get<HistoryItemDto[]>(`/api/history?${params}`)
      setItems(data ?? [])
    } catch {
      enqueueSnackbar('Failed to load history', { variant: 'error' })
    } finally {
      setLoading(false)
    }
  }, [currentMonth, search, categoryId, enqueueSnackbar])

  useEffect(() => { fetchCategories() }, [fetchCategories])
  useEffect(() => { fetchHistory() }, [fetchHistory])

  const handleDelete = async () => {
    if (!deleteItem) return
    try {
      await apiClient.delete(`/api/history/${deleteItem.id}`)
      enqueueSnackbar('Transaction deleted', { variant: 'success' })
      setDeleteItem(null)
      fetchHistory()
    } catch {
      enqueueSnackbar('Failed to delete transaction', { variant: 'error' })
    }
  }

  const totalForItem = (item: HistoryItemDto) =>
    item.details.reduce((sum, d) => sum + d.amount, 0)

  return (
    <Box>
      <Typography variant="h5" gutterBottom>History</Typography>

      {/* Filters */}
      <Paper sx={{ p: 2, mb: 2, display: 'flex', flexWrap: 'wrap', gap: 2, alignItems: 'center' }}>
        <Button variant="outlined" size="small" onClick={() => setCurrentMonth(d => new Date(d.getFullYear(), d.getMonth() - 1, 1))} startIcon={<ChevronLeft />}>Prev</Button>
        <Typography sx={{ minWidth: 140, textAlign: 'center' }}>
          {currentMonth.toLocaleString('default', { month: 'long', year: 'numeric' })}
        </Typography>
        <Button variant="outlined" size="small" onClick={() => setCurrentMonth(d => new Date(d.getFullYear(), d.getMonth() + 1, 1))} endIcon={<ChevronRight />}>Next</Button>

        <TextField
          label="Search"
          size="small"
          value={search}
          onChange={e => setSearch(e.target.value)}
          sx={{ minWidth: 200 }}
        />

        <FormControl size="small" sx={{ minWidth: 180 }}>
          <InputLabel>Category</InputLabel>
          <Select
            label="Category"
            value={categoryId}
            onChange={e => setCategoryId(e.target.value as number | '')}
          >
            <MenuItem value="">All</MenuItem>
            {categories.map(c => (
              <MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>
            ))}
          </Select>
        </FormControl>
      </Paper>

      {loading ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', p: 4 }}><CircularProgress /></Box>
      ) : (
        <List>
          {items.length === 0 && (
            <ListItem><ListItemText primary="No transactions found." /></ListItem>
          )}
          {items.map(item => (
            <Paper key={item.id} sx={{ mb: 1 }}>
              <ListItem
                secondaryAction={
                  <IconButton edge="end" color="error" onClick={() => setDeleteItem(item)}>
                    <Delete />
                  </IconButton>
                }
              >
                <ListItemText
                  primary={
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <Typography>
                        {new Date(item.date).toLocaleDateString()} — {item.description}
                        {item.isTransfer && <Chip size="small" label="Transfer" sx={{ ml: 1 }} />}
                      </Typography>
                      <Typography sx={{ fontWeight: 'bold' }}>{formatCents(totalForItem(item))}</Typography>
                    </Box>
                  }
                  secondary={
                    <Box component="span" sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5, mt: 0.5 }}>
                      {item.details.map(d => (
                        <Chip key={d.id} size="small" label={`${d.categoryName}: ${formatCents(d.amount)}`} variant="outlined" />
                      ))}
                    </Box>
                  }
                />
              </ListItem>
            </Paper>
          ))}
        </List>
      )}

      <Tooltip title="Add Transaction">
        <Fab color="primary" sx={{ position: 'fixed', bottom: 32, right: 32 }} onClick={() => setDialogOpen(true)}>
          <Add />
        </Fab>
      </Tooltip>

      <AddTransactionDialog
        open={dialogOpen}
        onClose={() => setDialogOpen(false)}
        categories={categories}
        onSuccess={() => { fetchHistory(); setDialogOpen(false) }}
      />

      {/* Delete Confirm Dialog */}
      <Dialog open={!!deleteItem} onClose={() => setDeleteItem(null)}>
        <DialogTitle>Confirm Delete</DialogTitle>
        <DialogContent>
          <DialogContentText>
            Delete transaction "{deleteItem?.description}"?
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDeleteItem(null)}>Cancel</Button>
          <Button color="error" onClick={handleDelete}>Delete</Button>
        </DialogActions>
      </Dialog>
    </Box>
  )
}
