// SimplyBudgetWeb.Web/src/components/AddTransactionDialog.tsx
import { useState } from 'react'
import {
  Dialog, DialogTitle, DialogContent, DialogActions, Button, TextField,
  Tab, Tabs, Box, MenuItem, Select, InputLabel, FormControl, IconButton,
  Typography, CircularProgress,
} from '@mui/material'
import { Add, Remove } from '@mui/icons-material'
import { useSnackbar } from 'notistack'
import { apiClient } from '@/services/apiClient'
import { ExpenseCategoryDto, TransactionRequest, TransferRequest } from '@/types'

interface Props {
  open: boolean
  onClose: () => void
  categories: ExpenseCategoryDto[]
  onSuccess: () => void
}

interface LineItem {
  expenseCategoryId: number | ''
  amount: string
}

const emptyLine = (): LineItem => ({ expenseCategoryId: '', amount: '' })

function LineItems({
  items,
  categories,
  onChange,
}: {
  items: LineItem[]
  categories: ExpenseCategoryDto[]
  onChange: (items: LineItem[]) => void
}) {
  const update = (index: number, patch: Partial<LineItem>) => {
    onChange(items.map((item, i) => (i === index ? { ...item, ...patch } : item)))
  }
  const remove = (index: number) => onChange(items.filter((_, i) => i !== index))
  const add = () => onChange([...items, emptyLine()])

  return (
    <Box>
      {items.map((item, index) => (
        <Box key={index} sx={{ display: 'flex', gap: 1, mb: 1, alignItems: 'center' }}>
          <FormControl size="small" sx={{ flex: 2 }}>
            <InputLabel>Category</InputLabel>
            <Select
              label="Category"
              value={item.expenseCategoryId}
              onChange={e => update(index, { expenseCategoryId: e.target.value as number | '' })}
            >
              {categories.map(c => (
                <MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>
              ))}
            </Select>
          </FormControl>
          <TextField
            size="small"
            label="Amount ($)"
            type="number"
            slotProps={{ htmlInput: { step: '0.01', min: '0' } }}
            value={item.amount}
            onChange={e => update(index, { amount: e.target.value })}
            sx={{ flex: 1 }}
          />
          {items.length > 1 && (
            <IconButton size="small" onClick={() => remove(index)}><Remove /></IconButton>
          )}
        </Box>
      ))}
      <Button size="small" startIcon={<Add />} onClick={add}>Add Line</Button>
    </Box>
  )
}

export default function AddTransactionDialog({ open, onClose, categories, onSuccess }: Props) {
  const [tab, setTab] = useState(0)
  const [description, setDescription] = useState('')
  const [date, setDate] = useState(() => new Date().toISOString().split('T')[0])
  const [lines, setLines] = useState<LineItem[]>([emptyLine()])
  const [transferAmount, setTransferAmount] = useState('')
  const [fromCategoryId, setFromCategoryId] = useState<number | ''>('')
  const [toCategoryId, setToCategoryId] = useState<number | ''>('')
  const [submitting, setSubmitting] = useState(false)
  const { enqueueSnackbar } = useSnackbar()

  const resetForm = () => {
    setDescription('')
    setDate(new Date().toISOString().split('T')[0])
    setLines([emptyLine()])
    setTransferAmount('')
    setFromCategoryId('')
    setToCategoryId('')
  }

  const handleClose = () => {
    resetForm()
    onClose()
  }

  const dollarsToCents = (s: string) => Math.round(parseFloat(s) * 100)

  const handleSubmit = async () => {
    setSubmitting(true)
    try {
      if (tab === 0 || tab === 1) {
        const endpoint = tab === 0 ? '/api/transactions/transaction' : '/api/transactions/income'
        const payload: TransactionRequest = {
          description,
          date,
          items: lines
            .filter(l => l.expenseCategoryId !== '' && l.amount !== '')
            .map(l => ({
              expenseCategoryId: l.expenseCategoryId as number,
              amount: dollarsToCents(l.amount),
            })),
        }
        await apiClient.post(endpoint, payload)
        enqueueSnackbar(tab === 0 ? 'Transaction added' : 'Income added', { variant: 'success' })
      } else {
        const payload: TransferRequest = {
          description,
          date,
          amount: dollarsToCents(transferAmount),
          fromCategoryId: fromCategoryId as number,
          toCategoryId: toCategoryId as number,
        }
        await apiClient.post('/api/transactions/transfer', payload)
        enqueueSnackbar('Transfer added', { variant: 'success' })
      }
      resetForm()
      onSuccess()
    } catch (e: unknown) {
      enqueueSnackbar(e instanceof Error ? e.message : 'Failed to save', { variant: 'error' })
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Dialog open={open} onClose={handleClose} maxWidth="sm" fullWidth>
      <DialogTitle>Add Transaction</DialogTitle>
      <DialogContent>
        <Tabs value={tab} onChange={(_, v) => setTab(v)} sx={{ mb: 2 }}>
          <Tab label="Transaction" />
          <Tab label="Income" />
          <Tab label="Transfer" />
        </Tabs>

        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          <TextField
            label="Description"
            fullWidth
            value={description}
            onChange={e => setDescription(e.target.value)}
          />
          <TextField
            label="Date"
            type="date"
            fullWidth
            value={date}
            onChange={e => setDate(e.target.value)}
            slotProps={{ inputLabel: { shrink: true } }}
          />

          {(tab === 0 || tab === 1) && (
            <>
              <Typography variant="subtitle2">Items</Typography>
              <LineItems items={lines} categories={categories} onChange={setLines} />
            </>
          )}

          {tab === 2 && (
            <>
              <TextField
                label="Amount ($)"
                type="number"
                slotProps={{ htmlInput: { step: '0.01', min: '0' } }}
                fullWidth
                value={transferAmount}
                onChange={e => setTransferAmount(e.target.value)}
              />
              <FormControl fullWidth>
                <InputLabel>From Category</InputLabel>
                <Select
                  label="From Category"
                  value={fromCategoryId}
                  onChange={e => setFromCategoryId(e.target.value as number | '')}
                >
                  {categories.map(c => <MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}
                </Select>
              </FormControl>
              <FormControl fullWidth>
                <InputLabel>To Category</InputLabel>
                <Select
                  label="To Category"
                  value={toCategoryId}
                  onChange={e => setToCategoryId(e.target.value as number | '')}
                >
                  {categories.map(c => <MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}
                </Select>
              </FormControl>
            </>
          )}
        </Box>
      </DialogContent>
      <DialogActions>
        <Button onClick={handleClose}>Cancel</Button>
        <Button variant="contained" onClick={handleSubmit} disabled={submitting}>
          {submitting ? <CircularProgress size={20} aria-label="Saving transaction" /> : 'Save'}
        </Button>
      </DialogActions>
    </Dialog>
  )
}

// SimplyBudgetWeb.Web/src/components/AddTransactionDialog.vue
<script setup lang="ts">
import { ref } from 'vue'
import { apiClient } from '@/services/apiClient'
import { useSnackbarStore } from '@/stores/snackbar'
import type { ExpenseCategoryDto, TransactionRequest, TransferRequest } from '@/types'

const props = defineProps<{
  modelValue: boolean
  categories: ExpenseCategoryDto[]
}>()

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  success: []
}>()

const snackbar = useSnackbarStore()

interface LineItem {
  expenseCategoryId: number | null
  amount: string
}

const emptyLine = (): LineItem => ({ expenseCategoryId: null, amount: '' })

const tab = ref<'transaction' | 'income' | 'transfer'>('transaction')
const description = ref('')
const date = ref(new Date().toISOString().split('T')[0])
const lines = ref<LineItem[]>([emptyLine()])
const transferAmount = ref('')
const fromCategoryId = ref<number | null>(null)
const toCategoryId = ref<number | null>(null)
const submitting = ref(false)

function addLine() {
  lines.value.push(emptyLine())
}

function removeLine(index: number) {
  lines.value = lines.value.filter((_, i) => i !== index)
}

function resetForm() {
  description.value = ''
  date.value = new Date().toISOString().split('T')[0]
  lines.value = [emptyLine()]
  transferAmount.value = ''
  fromCategoryId.value = null
  toCategoryId.value = null
  tab.value = 'transaction'
}

function close() {
  resetForm()
  emit('update:modelValue', false)
}

function dollarsToCents(s: string) {
  return Math.round(parseFloat(s) * 100)
}

async function submit() {
  submitting.value = true
  try {
    if (tab.value === 'transaction' || tab.value === 'income') {
      const endpoint = tab.value === 'transaction' ? '/api/transactions/transaction' : '/api/transactions/income'
      const payload: TransactionRequest = {
        description: description.value,
        date: date.value,
        items: lines.value
          .filter(l => l.expenseCategoryId !== null && l.amount !== '')
          .map(l => ({
            expenseCategoryId: l.expenseCategoryId as number,
            amount: dollarsToCents(l.amount),
          })),
      }
      await apiClient.post(endpoint, payload)
      snackbar.enqueueSnackbar(tab.value === 'transaction' ? 'Transaction added' : 'Income added', { variant: 'success' })
    } else {
      const payload: TransferRequest = {
        description: description.value,
        date: date.value,
        amount: dollarsToCents(transferAmount.value),
        fromCategoryId: fromCategoryId.value as number,
        toCategoryId: toCategoryId.value as number,
      }
      await apiClient.post('/api/transactions/transfer', payload)
      snackbar.enqueueSnackbar('Transfer added', { variant: 'success' })
    }
    resetForm()
    emit('success')
  } catch (e: unknown) {
    snackbar.enqueueSnackbar(e instanceof Error ? e.message : 'Failed to save', { variant: 'error' })
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <v-dialog :model-value="props.modelValue" max-width="600" @update:model-value="(val: boolean) => !val && close()">
    <v-card>
      <v-card-title>Add Transaction</v-card-title>
      <v-card-text>
        <v-tabs v-model="tab" class="mb-4">
          <v-tab value="transaction">Transaction</v-tab>
          <v-tab value="income">Income</v-tab>
          <v-tab value="transfer">Transfer</v-tab>
        </v-tabs>

        <div class="d-flex flex-column" style="gap: 16px;">
          <v-text-field label="Description" v-model="description" />
          <v-text-field label="Date" type="date" v-model="date" />

          <template v-if="tab === 'transaction' || tab === 'income'">
            <span class="text-subtitle-2">Items</span>
            <div v-for="(item, index) in lines" :key="index" class="d-flex align-center mb-2" style="gap: 8px;">
              <v-select
                label="Category"
                :items="props.categories"
                item-title="name"
                item-value="id"
                v-model="item.expenseCategoryId"
                style="flex: 2;"
                density="compact"
              />
              <v-text-field
                label="Amount ($)"
                type="number"
                step="0.01"
                min="0"
                v-model="item.amount"
                style="flex: 1;"
                density="compact"
              />
              <v-btn v-if="lines.length > 1" icon="mdi-minus" size="small" variant="text" aria-label="Remove line" @click="removeLine(index)" />
            </div>
            <v-btn size="small" prepend-icon="mdi-plus" variant="text" @click="addLine">Add Line</v-btn>
          </template>

          <template v-else>
            <v-text-field label="Amount ($)" type="number" step="0.01" min="0" v-model="transferAmount" />
            <v-select label="From Category" :items="props.categories" item-title="name" item-value="id" v-model="fromCategoryId" />
            <v-select label="To Category" :items="props.categories" item-title="name" item-value="id" v-model="toCategoryId" />
          </template>
        </div>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn @click="close">Cancel</v-btn>
        <v-btn color="primary" :loading="submitting" @click="submit">Save</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>
